backstage/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.getBackstage, name="userAccoundAll"),
    path('logout/', views.userLoginOut, name="userLoginOut"),
    path('getUser/<str:name>/', views.getUserInformation, name="getUserInfo"),
    path('getUserInfo/', views.getUserInfo, name="userInfo"),
    path('addmoney/', views.addmoney, name="addmoney"),
    path('paymoney/', views.paymoney, name="paymoney"),
    path('borrowmoney/', views.borrowmoney, name="borrowmoney"),
    path('lendmoney/', views.lendmoney, name="lendmoney"),
    path('getMessage/', views.getMessage, name="getMessage"),
    path('delUser/<str:name>/', views.delUser, name="delUser"),
]

userControl/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('checkpoint.urls', 'account'), namespace='account')),
    path('backstage/', include(('backstage.urls', 'backstage'), namespace='backstage'))
]

backstage/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import datetime


class UserInfo(AbstractUser):
    sexs = (
        ('male', u'男'),
        ('female', u'女')
    )
    introduction = models.TextField(max_length=200, null=True, blank=False, verbose_name=u'个人简介')
    qq = models.CharField(max_length=16, null=True, blank=False, verbose_name=u'QQ')
    phone = models.CharField(max_length=11, null=True, blank=False, verbose_name=u'手机号')
    sex = models.CharField(max_length=6, null=False, blank=False, verbose_name=u'性别', default='male', choices=sexs)
    birth = models.DateField(null=True, blank=True, verbose_name=u'出生日期',
                             default=datetime.datetime.now().strftime('%Y-%m-%d'))

    def __str__(self):
        return self.first_name


class mhealth(models.Model):
    weight = models.CharField(max_length=100, verbose_name=u'体重',null=True)
    blood_pressure = models.CharField(max_length=111, verbose_name=u'血压', null=True)
    routine_blood_test = models.CharField(max_length=100, verbose_name=u'血常规', null=True)

    def __str__(self):
        return self.creatUser


class paymoneyin(models.Model):
    amount = models.CharField(max_length=100, verbose_name=u'金额')
    article = models.CharField(max_length=111, verbose_name=u'项目', null=True)
    datetime = models.DateField(verbose_name=u'日期', default=datetime.datetime.now().strftime('%Y-%m-%d'))
    creatUser = models.CharField(max_length=100, verbose_name=u'创建人', null=True)

    def __str__(self):
        return self.creatUser

class borrowmoneyin(models.Model):
    amount = models.CharField(max_length=100, verbose_name=u'金额')
    article = models.CharField(max_length=111, verbose_name=u'项目', null=True)
    datetime = models.DateField(verbose_name=u'日期', default=datetime.datetime.now().strftime('%Y-%m-%d'))
    creatUser = models.CharField(max_length=100, verbose_name=u'创建人', null=True)
    name = models.CharField(max_length=100, verbose_name=u'所属人', null=True)

    def __str__(self):
        return self.creatUser

class lendmoneyin(models.Model):
    amount = models.CharField(max_length=100, verbose_name=u'金额')
    article = models.CharField(max_length=111, verbose_name=u'项目', null=True)
    datetime = models.DateField(verbose_name=u'日期', default=datetime.datetime.now().strftime('%Y-%m-%d'))
    creatUser = models.CharField(max_length=100, verbose_name=u'创建人', null=True)

    def __str__(self):
        return self.creatUser

backstage/views.py
from django.shortcuts import render, redirect, HttpResponse
from backstage.models import UserInfo, mhealth, paymoneyin, lendmoneyin, borrowmoneyin
from django.contrib.auth import logout
from django.contrib.auth.hashers import make_password
import json

msg = ''


def getBackstage(request):
    response = 0
    if request.method == 'GET':
        crruentUser = request.user.username
        if crruentUser:
            if UserInfo.objects.get(username=crruentUser).is_active:
                user_all_information = UserInfo.objects.all()
                name = crruentUser
                response = render(request, 'account.html',
                                  {'username': name, 'user_all_information': user_all_information})
            else:
                response = redirect('/')
        else:
            tips = "请先登录"
            response = redirect('/', locals())
    else:
        response = redirect('/')
    return response


def userLoginOut(request):
    crruentUser = request.user.username
    if crruentUser:
        if UserInfo.objects.get(username=crruentUser).is_active:
            logout(request)
            return redirect('/')
        else:
            return redirect('/', locals())
    else:
        return redirect('/')


def getUserInformation(request, name):
    if request.is_ajax():
        crruentUser = request.user.username
        if crruentUser:
            if UserInfo.objects.get(username=crruentUser).is_active:
                try:
                    if name == 'currentUser':
                        user_all_information = UserInfo.objects.get(username=crruentUser)
                    else:
                        user_all_information = UserInfo.objects.get(username=name)
                    information = {}
                    information['introduction'] = user_all_information.introduction
                    information['qq'] = user_all_information.qq
                    information['phone'] = user_all_information.phone
                    information['username'] = user_all_information.username
                    information['email'] = user_all_information.email
                    information['first_name'] = user_all_information.first_name
                    return HttpResponse(json.dumps(information))
                except Exception as e:
                    print(e)
                    return HttpResponse('bad request 500')
            else:
                return redirect('/', locals())
        else:
            return redirect('/')
    else:
        return HttpResponse('bad request 500')


def getUserInfo(request):
    global msg

    if request.method == 'GET':
        crruentUser = request.user.username
        if crruentUser:
            if UserInfo.objects.get(username=crruentUser).is_active:
                userinfo = UserInfo.objects.get(username=crruentUser)
                msg = ''
                return render(request, 'userinfo.html', {'userinfo': userinfo, 'msg': msg})
            else:
                return redirect('/', locals())
        else:
            return redirect('/')
    elif request.is_ajax() or request.method == 'POST':
        crruentUser = request.user.username
        if crruentUser:
            user = UserInfo.objects.get(username=crruentUser)
            change_info = request.POST
            for key, value in change_info.items():
                if key != "csrfmiddlewaretoken":
                    try:
                        if key == 'password':
                            exec('user.' + key + '="' + str(make_password(value)) + '"')
                        else:
                            exec('user.' + key + '="' + value + '"')
                    except Exception as e:
                        print(e)
                        msg = "修改失败"
            try:
                user.save()
                msg = '修改成功'
            except Exception as e:
                print(e)
                msg = "修改失败 " + str(e)
            return render(request, 'userinfo.html', locals())
        else:
            return redirect('/')
    else:
        return HttpResponse('bad request 500')


def addmoney(request):
    if request.method == 'GET':
        moneyInfo_List = mhealth.objects.all()
        return render(request, 'addmoney.html', {'moneyInfo_List': moneyInfo_List})
    if request.method == 'POST':


    # mhealth.objects.create(weight=weight, blood_pressure=blood_pressure, routine_blood_test=routine_blood_test)

        edit_publisher = mhealth.objects.get(id=1)
        edit_publisher.weight = request.POST.get('weight')
        edit_publisher.blood_pressure = request.POST.get('blood_pressure')
        edit_publisher.routine_blood_test = request.POST.get('routine_blood_test')

        if len(edit_publisher.weight) == 0:
            moneyInfo_List = mhealth.objects.all()
            return render(request, 'addmoney.html', {'moneyInfo_List': moneyInfo_List})

        if len(edit_publisher.blood_pressure) == 0:
            moneyInfo_List = mhealth.objects.all()
            return render(request, 'addmoney.html', {'moneyInfo_List': moneyInfo_List})

        if len(edit_publisher.routine_blood_test) == 0:
            moneyInfo_List = mhealth.objects.all()
            return render(request, 'addmoney.html', {'moneyInfo_List': moneyInfo_List})

        edit_publisher.save()  # 把修改提交到数据库

        moneyInfo_List = mhealth.objects.all()
        return render(request, 'addmoney.html', {'moneyInfo_List': moneyInfo_List})
    else:
        return HttpResponse('bad request 500')


def paymoney(request):
    if request.method == 'GET':
        moneyInfo_List = paymoneyin.objects.all()
        return render(request, 'paymoney.html', {'moneyInfo_List': moneyInfo_List})
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        password = request.POST.get('password')
        repassword = request.POST.get('repassword')
        paymoneyin.objects.create(amount=name, article=password, creatUser=email, datetime=repassword)
        moneyInfo_List = paymoneyin.objects.all()
        return render(request, 'paymoney.html', {'moneyInfo_List': moneyInfo_List})
    else:
        return HttpResponse('bad request 500')


def borrowmoney(request):
    if request.method == 'GET':
        moneyInfo_List = borrowmoneyin.objects.all()
        return render(request, 'borrowmoney.html', {'moneyInfo_List': moneyInfo_List})
    if request.method == 'POST':
        weight = request.POST.get('weight')
        blood_pressure = request.POST.get('blood_pressure')
        routine_blood_test = request.POST.get('routine_blood_test')
        name = request.user.username
        data = request.POST.get('data')

        if len(weight) == 0:
            moneyInfo_List = borrowmoneyin.objects.all()
            return render(request, 'borrowmoney.html', {'moneyInfo_List': moneyInfo_List})
        if len(routine_blood_test) == 0:
            moneyInfo_List = borrowmoneyin.objects.all()
            return render(request, 'borrowmoney.html', {'moneyInfo_List': moneyInfo_List})
        if len(blood_pressure) == 0:
            moneyInfo_List = borrowmoneyin.objects.all()
            return render(request, 'borrowmoney.html', {'moneyInfo_List': moneyInfo_List})

        rel_edit_publisher = mhealth.objects.get(id=1)
        rel_weight = rel_edit_publisher.weight
        rel_blood_pressure = rel_edit_publisher.blood_pressure
        rel_routine_blood_test = rel_edit_publisher.routine_blood_test

        strlist = rel_weight.split('-')
        if int(weight) < int(strlist[0]):
            weight = weight + '  偏低'
        elif int(weight) > int(strlist[1]):
            weight = weight + '  偏高'

        strlist2 = rel_blood_pressure.split('-')
        if int(blood_pressure) < int(strlist2[0]):
            blood_pressure = blood_pressure + '  偏低'
        elif int(blood_pressure) > int(strlist2[1]):
            blood_pressure = blood_pressure + '  偏高'

        strlist3 = rel_routine_blood_test.split('-')
        if float(routine_blood_test) < float(strlist3[0]):
            routine_blood_test = routine_blood_test + '  偏低'
        elif float(routine_blood_test) > float(strlist3[1]):
            routine_blood_test = routine_blood_test + '  偏高'



        borrowmoneyin.objects.create(amount=weight, article=blood_pressure, creatUser=routine_blood_test, datetime=data, name=name)
        moneyInfo_List = borrowmoneyin.objects.all()
        return render(request, 'borrowmoney.html', {'moneyInfo_List': moneyInfo_List})
    else:
        return HttpResponse('bad request 500')


def lendmoney(request):
    if request.method == 'GET':
        moneyInfo_List = lendmoneyin.objects.all()
        return render(request, 'lendmoney.html', {'moneyInfo_List': moneyInfo_List})
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        password = request.POST.get('password')
        repassword = request.POST.get('repassword')
        lendmoneyin.objects.create(amount=name, article=password, creatUser=email, datetime=repassword)
        moneyInfo_List = lendmoneyin.objects.all()
        return render(request, 'lendmoney.html', {'moneyInfo_List': moneyInfo_List})
    else:
        return HttpResponse('bad request 500')


def getMessage(request):
    global msg

    if request.is_ajax():
        crruentUser = request.user.username
        if crruentUser:
            return HttpResponse(msg)
        else:
            return HttpResponse('bad request 500')
    else:
        return HttpResponse('bad request 500')


def delUser(request, name):
    if request.is_ajax():
        crruentUser = request.user.username
        if crruentUser:
            if name.upper() != crruentUser.upper():
                if UserInfo.objects.get(username=crruentUser).is_superuser:
                    try:
                        UserInfo.objects.get(username=name).delete()
                        msg = '删除成功'

backstage/templates/account.html
{% load static %}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>账户管理</title>
    <link href="{% static 'backstage/css/bootstrap.css' %}" rel="stylesheet" />
    <link href="{% static 'backstage/css/font-awesome.css' %}" rel="stylesheet" />
    <link href="{% static 'backstage/css/custom-styles.css' %}" rel="stylesheet" />
    <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
    <link href="{% static 'backstage/js/dataTables/dataTables.bootstrap.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'backstage/css/toastr.min.css' %}">
</head>
<body>
    <div id="wrapper">
        <nav class="navbar navbar-default top-navbar" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="javascript:;"><strong>家庭健康管理系统</strong></a>
            </div>

            <h1 class="username">欢迎，&nbsp;{{ username }}</h1>

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:;" aria-expanded="false">
                        <i class="fa fa-envelope fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-messages">
                    	<!-- 消息循环开始 -->
                        <li>
                            <a href="javascript:;">
                                <div>
                                    <strong>John Doe</strong>
                                    <span class="pull-right text-muted">
                                        <em>Today</em>
                                    </span>
                                </div>
                                <div>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <!-- 消息循环结束 -->
                        <li>
                            <a class="text-center" href="javascript:;">
                                <strong>所有消息</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:;" aria-expanded="false">
                        <i class="fa fa-tasks fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-tasks">
                    	<!-- 任务循环开始 -->
                        <li>
                            <a href="javascript:;">
                                <div>
                                    <p>
                                        <strong>Task 1</strong>
                                        <span class="pull-right text-muted">60% 完成</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                            <span class="sr-only">60% Complete (success)</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <!-- 任务循环结束 -->
                        <li>
                            <a class="text-center" href="javascript:;">
                                <strong>查看所有任务</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:;" aria-expanded="false">
                        <i class="fa fa-bell fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-alerts">
                    	<!-- 提醒循环开始 -->
                        <li>
                            <a href="javascript:;">
                                <div>
                                    <i class="fa fa-comment fa-fw"></i> New Comment
                                    <span class="pull-right text-muted small">4 min</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <!-- 提醒循环结束 -->
                        <li>
                            <a class="text-center" href="javascript:;">
                                <strong>查看所有提醒</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:;" aria-expanded="false">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="{% url 'backstage:userInfo' %}"><i class="fa fa-user fa-fw"></i>用户资料</a>
                        </li>
                        <li><a href="{% url 'backstage:addmoney' %}"><i class="fa fa-gear fa-fw"></i>设置</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="{% url 'backstage:userLoginOut' %}"><i class="fa fa-sign-out fa-fw"></i>注销</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
        <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">

                    <li>
                        <a href="{% url 'backstage:userAccoundAll' %}" class="active-menu"><i class="fa fa-table"></i>账户管理</a>
                    </li>
					 <li><a href="{% url 'backstage:userInfo' %}"><i class="fa fa-user fa-fw"></i>用户资料</a>
                        </li>
					<!-- 多级下拉菜单控件 -->
                    <li>
                        <a href="{% url 'backstage:borrowmoney' %}"><i class="fa fa-user fa-fw"></i>家庭健康管理</a>
                    </li>
                    <li><a href="{% url 'backstage:addmoney' %}"><i class="fa fa-gear fa-fw"></i>设置</a>
                        </li>
                </ul>

            </div>
        </nav>
        <div id="page-wrapper" >
		  <div class="header">
                        <h1 class="page-header">
                            账户管理 <small>账户提权、删除、添加、更改信息</small>
                        </h1>
						<ol class="breadcrumb">
					  <li><a href="javascript:;">主页</a></li>
					  <li><a href="javascript:;">账户管理</a></li>
					  <li><a href="javascript:;">所有账户</a></li>
					</ol>
		</div>
        <div id="page-inner">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            所有账户
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th>用户名</th>
                                            <th>姓名</th>
                                            <th>注册时间</th>
                                            <th>上次登录时间</th>
                                            <th>是否为管理员</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    {% for user in user_all_information %}
                                        <tr class="odd gradeX">
                                            <td><a href="javascript:;" class="get-user">{{ user.username }}</a></td>
                                            <td>{{ user.first_name }}</td>
                                            <td>{{ user.date_joined }}</td>
                                            <td class="center">{{ user.last_login }}</td>
                                            <td class="center">{{ user.is_superuser }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row user-information">
              <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                  <div class="caption">
                    <h3 class="user-information-name"></h3>
                    <p class="user-information-email"></p>
                    <p><a href="javascript:;" class="btn btn-danger" role="button" id="deleteUser">删除</a></p>
                  </div>
                </div>
              </div>
            </div>
        </div>
    </div>
    <script src="{% static 'backstage/js/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'backstage/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'backstage/js/jquery.metisMenu.js' %}"></script>
    <script src="{% static 'backstage/js/dataTables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'backstage/js/dataTables/dataTables.bootstrap.js' %}"></script>
    <script src="{% static 'backstage/js/toastr.min.js' %}"></script>
    <script src="{% static 'backstage/js/layer.js' %}"></script>
    <script>

        toastr.options = { closeButton: !0, debug: !1, newestOnTop: !1, progressBar: !1, positionClass: "toast-bottom-full-width", preventDuplicates: !1, onclick: null, showDuration: "300", hideDuration: "1000", timeOut: "5000", extendedTimeOut: "1000", showEasing: "swing", hideEasing: "linear", showMethod: "slideDown", hideMethod: "fadeOut" }
        $(document).ready(function () {
            $('#dataTables-example').dataTable({
                dom: 'Bfrtip',
                buttons: ['remove']
            });
        });
        $('.get-user').click(
            function () {
                let username = this.innerText;
                $.ajax({
                    url: 'getUser/' + username + '/',
                    type: 'get',
                    success: function (data) {
                        let dataObj = JSON.parse(data);
                        $('.user-information-name').text(dataObj['username']);
                        $('.user-information-email').text(dataObj['email']);
                    }
                })
            }
        );
        $('#deleteUser').click(function () {
            let name = $('.user-information-name').text();
            $.ajax({
                url: 'delUser/' + name + '/',
                type: 'get',
                success: function (data) {
                    let msg;
                    data.responseText?msg = data.responseText:msg = data;
                    toastr.success(msg);
                },
                error: function (data) {
                    let msg;
                    data.responseText?msg = data.responseText:msg = data;
                    toastr.success(msg);
                    setTimeout(function(){
                        window.location.reload();
                    }, 1000)
                }
            });
        });
        setInterval(function () {
            $('.user-information-name').text()?$('.user-information').css('display', 'block'):$('.user-information').css('display', 'none');
        }, 100);
    </script>
    <script src="{% static 'backstage/js/custom-scripts.js' %}"></script>


</body>
</html>