backstage/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.getBackstage, name="userAccoundAll"),
    path('logout/', views.userLoginOut, name="userLoginOut"),
    path('getUser/<str:name>/', views.getUserInformation, name="getUserInfo"),
    path('getUserInfo/', views.getUserInfo, name="userInfo"),
    path('addmoney/', views.addmoney, name="addmoney"),
    path('paymoney/', views.paymoney, name="paymoney"),
    path('borrowmoney/', views.borrowmoney, name="borrowmoney"),
    path('lendmoney/', views.lendmoney, name="lendmoney"),
    path('getMessage/', views.getMessage, name="getMessage"),
    path('delUser/<str:name>/', views.delUser, name="delUser"),
]

checkpoint/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.getlogin, name='userlogin'),
    path('register', views.getregister, name='userregister'),
    path('forget', views.getforget, name='userforget')
]

userControl/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('checkpoint.urls', 'account'), namespace='account')),
    path('backstage/', include(('backstage.urls', 'backstage'), namespace='backstage'))
]

checkpoint/models.py
from django.db import models

checkpoint/views.py
from django.shortcuts import render, redirect
from backstage.models import UserInfo
from django.contrib.auth import login, authenticate


def getlogin(request):
    title = '家庭健康管理系统-登录'
    if request.method == 'POST':
        name = request.POST.get('username')
        password = request.POST.get('userpassword')
        try:
            user = UserInfo.objects.get(username=name)
        except Exception as e:
            print(e)
            user = False
        if user:
            checkPassword = authenticate(username=name, password=password)
            if checkPassword:
                if checkPassword.is_active:
                    login(request, checkPassword)
                    tips = "登录成功"
                    return redirect('backstage/')
                else:
                    tips = "请先激活用户"
            else:
                tips = "密码错误"
        else:
            tips = '用户不存在'
    else:
        crruentUser = request.user.username
        if str(crruentUser):
            if UserInfo.objects.get(username=crruentUser).is_active:
                return redirect('backstage/')
    return render(request, 'checkpoint.html', locals())


def getregister(request):
    title = '家庭健康管理系统-注册'
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        password = request.POST.get('password')
        repassword = request.POST.get('repassword')
        user = UserInfo.objects.all()
        if len(name) > 0 and len(email) > 0 and len(password) > 0 and len(repassword) > 0:
            if repassword == password:
                if len(password) >= 6:
                    if len(name) > 15:
                        tips = "用户名不能超过15个字符"
                    else:
                        if len(user.filter(username=name)) > 0:
                            tips = "用户名已存在"
                        else:
                            if len(user.filter(email=email)) > 0:
                                tips = "邮箱已被注册"
                            else:
                                try:
                                    UserInfo.objects.create_user(username=name, email=email, password=password)
                                    tips = "注册成功"
                                except Exception as e:
                                    print(e)
                                    tips = "注册失败"
                else:
                    tips = "密码太短，请输入 6 位或 6 位以上的密码"
            else:
                tips = "两次密码不一致"
        else:
            tips = "所有内容都不能为空"
    return render(request, 'signup.html', locals())


def getforget(request):
    title = '家庭健康管理系统-找回密码'
    return render(request, 'forget.html', {'title': title})

checkpoint/templates/checkpoint.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7"><![endif]-->
<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8"><![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9"><![endif]-->
<!--[if IE 8]><html class="no-js"><![endif]-->
	<html lang="zh">
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>{{ title }}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="" />
	<meta name="keywords" content="" />
  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />
	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="favicon.ico"> 
	<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="{% static 'checkpoint/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'checkpoint/css/animate.css' %}">
	<link rel="stylesheet" href="{% static 'checkpoint/css/style.css' %}">
	<script src="{% static 'checkpoint/js/modernizr-2.6.2.min.js' %}"></script>
	<!--[if lt IE 9]><script src="js/respond.min.js"></script><![endif]-->
	</head>
	<body>
		<div class="container">
			<div class="row">
				<div class="col-md-4 col-md-offset-4">
					<form action="{% url 'account:userlogin' %}" class="fh5co-form animate-box" data-animate-effect="fadeIn" method="post" id="logoForm">
                        {% csrf_token %}
						<h2>登入</h2>
                        {% if tips %}
						<div class="form-group">
							<div class="alert alert-warning" role="alert">{{ tips }}</div>
						</div>
                        {% endif %}
						<div class="form-group">
							<label for="username" class="sr-only">用户名</label>
							<input type="text" class="form-control" id="username" placeholder="用户名" autocomplete="off" name="username">
						</div>
						<div class="form-group">
							<label for="password" class="sr-only">密码</label>
							<input type="password" class="form-control" id="password" placeholder="密码" autocomplete="off" name="userpassword">
						</div>
						<div class="form-group">
							<p>还没有注册？<a href="{% url 'account:userregister' %}">点击注册</a> | <a href="{% url 'account:userforget' %}">忘记密码？</a></p>
						</div>
						<div class="form-group">
							<input type="submit" value="登录" class="btn btn-primary" id="login">
						</div>
					</form>
				</div>
			</div>

		</div>
	<script src="{% static 'checkpoint/js/jquery.min.js' %}"></script>
	<script src="{% static 'checkpoint/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'checkpoint/js/jquery.placeholder.min.js' %}"></script>
	<script src="{% static 'checkpoint/js/jquery.waypoints.min.js' %}"></script>
	<script src="{% static 'checkpoint/js/main.js' %}"></script>
	</body>
</html>

checkpoint/templates/forget.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7"><![endif]-->
<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8"><![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9"><![endif]-->
<!--[if IE 8]><html class="no-js"><![endif]-->
	<html lang="zh">
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>{{ title }}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="" />
	<meta name="keywords" content="" />
  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />
	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="favicon.ico"> 
	<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="{% static 'checkpoint/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'checkpoint/css/animate.css' %}">
	<link rel="stylesheet" href="{% static 'checkpoint/css/style.css' %}">
	<script src="{% static 'checkpoint/js/modernizr-2.6.2.min.js' %}"></script>
	<!--[if lt IE 9]><script src="js/respond.min.js"></script><![endif]-->
	</head>
	<body>

		<div class="container">
			<div class="row">
				<div class="col-md-4 col-md-offset-4">
					<form action="{% url 'account:userforget' %}" class="fh5co-form animate-box" data-animate-effect="fadeIn" method="post">
						{% csrf_token %}
						<h2>找回密码</h2>
                        {% if tips %}
						<div class="form-group">
							<div class="alert alert-warning" role="alert">{{ tips }}</div>
						</div>
                        {% endif %}
						<div class="form-group">
							<label for="email" class="sr-only">你的邮箱</label>
							<input type="email" class="form-control" id="email" placeholder="邮箱" autocomplete="off" name="email">
						</div>
						<div class="form-group">
							<p><a href="{% url 'account:userlogin' %}">登录</a> or <a href="{% url 'account:userregister' %}">注册</a></p>
						</div>
						<div class="form-group">
							<input type="submit" value="发送验证码" class="btn btn-primary">
						</div>
					</form>
				</div>
			</div>

		</div>
	<script src="{% static 'checkpoint/js/jquery.min.js' %}"></script>
	<script src="{% static 'checkpoint/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'checkpoint/js/jquery.placeholder.min.js' %}"></script>
	<script src="{% static 'checkpoint/js/jquery.waypoints.min.js' %}"></script>
	<script src="{% static 'checkpoint/js/main.js' %}"></script>
	</body>
</html>

checkpoint/templates/signup.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7"><![endif]-->
<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8"><![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9"><![endif]-->
<!--[if IE 8]><html class="no-js"><![endif]-->
	<html lang="zh">
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>{{ title }}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="" />
	<meta name="keywords" content="" />
  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />
	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="favicon.ico">

	<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="{% static 'checkpoint/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'checkpoint/css/animate.css' %}">
	<link rel="stylesheet" href="{% static 'checkpoint/css/style.css' %}">
	<script src="{% static 'checkpoint/js/modernizr-2.6.2.min.js' %}"></script>
	<!--[if lt IE 9]><script src="js/respond.min.js"></script><![endif]-->
	</head>
	<body>
		<div class="container">
			<div class="row">
				<div class="col-md-4 col-md-offset-4">
					<form action="{% url 'account:userregister' %}" class="fh5co-form animate-box" data-animate-effect="fadeIn" method="post">
						{% csrf_token %}
						<h2>注册</h2>
                        {% if tips %}
						<div class="form-group">
							<div class="alert alert-warning" role="alert">{{ tips }}</div>
						</div>
                        {% endif %}
						<div class="form-group">
							<label for="name" class="sr-only">用户名</label>
							<input type="text" class="form-control" id="name" placeholder="用户名" autocomplete="off" name="name">
						</div>
						<div class="form-group">
							<label for="email" class="sr-only">邮箱</label>
							<input type="email" class="form-control" id="email" placeholder="邮箱" autocomplete="off" name="email">
						</div>
						<div class="form-group">
							<label for="password" class="sr-only">密码</label>
							<input type="password" class="form-control" id="password" placeholder="密码" autocomplete="off" name="password">
						</div>
						<div class="form-group">
							<label for="re-password" class="sr-only">重复密码</label>
							<input type="password" class="form-control" id="re-password" placeholder="重复密码" autocomplete="off" name="repassword">
						</div>
						<div class="form-group">
							<p>已经注册了？<a href="{% url 'account:userlogin' %}">马上登录</a></p>
						</div>
						<div class="form-group">
							<input type="submit" value="注册" class="btn btn-primary">
						</div>
					</form>
				</div>
			</div>

		</div>
	<script src="{% static 'checkpoint/js/jquery.min.js' %}"></script>
	<script src="{% static 'checkpoint/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'checkpoint/js/jquery.placeholder.min.js' %}"></script>
	<script src="{% static 'checkpoint/js/jquery.waypoints.min.js' %}"></script>
	<script src="{% static 'checkpoint/js/main.js' %}"></script>
	</body>
</html>